FROM nginxproxy/nginx-proxy:alpine

COPY uploadsize.conf /etc/nginx/conf.d/
COPY vhost.d/mail.1mccormick.com /etc/nginx/vhost.d/mail.1mccormick.com
COPY vhost.d/mail.firestonelodging.com /etc/nginx/vhost.d/mail.firestonelodging.com
COPY vhost.d/mail.mccormick.sh /etc/nginx/vhost.d/mail.mccormick.sh