server:
    interface: 127.0.0.1
    interface: 172.19.1.1
    ip-transparent: yes
    port: 53
    access-control: 127.0.0.0/8 allow
    access-control: 172.19.1.0/27 allow
    root-hints: "/var/lib/unbound/root.hints"
    do-ip4: yes
    do-ip6: no
    hide-identity: yes
    hide-version: yes
    qname-minimisation: yes
    prefetch: yes
    rrset-roundrobin: yes
    cache-min-ttl: 300
    cache-max-ttl: 86400
    harden-glue: yes
    harden-dnssec-stripped: yes
    use-caps-for-id: yes
    verbosity: 0