FROM python:alpine

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE 1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED 1

# Set timezone to Denver
ARG TZ=America/Denver
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezone

ADD requirements.txt .
RUN pip install --upgrade pip && python -m pip install --no-cache-dir -r requirements.txt

WORKDIR /app
ADD . /app