group "phishing" {
  max_score = 10;
}

group "rbl" {
  symbols {
    RBL_SPAMCOP {
      score = 3.0;
    }
    RBL_SPAMHAUS_DBL {
      score = 3.5;
    }
  }
}

symbols {
  REPLYTO_DOM_NEQ_FROM_DOM {
    weight = 6.0;
  }

  REPLYTO_DOM_NEQ_TO_DOM {
    weight = 5.5;
  }

  R_SPF_SOFTFAIL {
    weight = 1.5;
  }

  HFILTER_HOSTNAME_UNKNOWN {
    weight = 3.0;
  }  

  ASN {
    weight = 0.5;
  }  

  BAYES_SPAM {
    weight = 6.5;
  }  
}