regexp {
  ACME_CHALLENGE_SPAM = {
    re = "\\.well-known.*acme-challenge";
    score = 3.0;
  }

  FAKE_GOV_SENDER = {
    re = "@(irs|ssa|socialsecurity)[-_.].*\\.(co|info|biz)";
    score = 3.5;
  }
}