duck_alias_recipient {
  from = "@duck.com";
  priority = high;

  apply {
    score = 0;
    actions {
      reject = null;
      soft_reject = null;
    }
    symbols_disabled = ["GREYLIST"];
  }
}

intuit_quickbooks_authenticated {
  priority = high;
  from = "/@(e\\.)?notification\\.intuit\\.com$/";
  authenticated = false;
  apply {
    symbols_disabled = [
      "REPLYTO_DOM_NEQ_FROM_DOM",
      "REPLYTO_DOM_NEQ_TO_DOM"
    ];
    symbols {
      "INTUIT_QUICKBOOKS_AUTHENTICATED" {
        score = -8.0;
      }
    }
  }
}
