duck_alias_recipient {
  from = "@duck.com";
  priority = high;

  apply {
    actions {
      reject = null;
      soft_reject = null;
      add_header = null;
    }
    symbols_disabled = ["GREYLIST"];
  }
}
