rbls = {

  spamhaus {
    symbol = "SPAMHAUS";
    rbl = "zen.spamhaus.org";
    checks = ["from", "received"];
  }

  DBL {
    rbl = "dbl.spamhaus.org";
    checks = ["emails", "dkim", "helo", "rdns", "replyto", "urls", "content_urls"];
    no_ip = true;
  }
}