FROM alpine

RUN apk add --no-cache opendkim opendkim-utils dumb-init

RUN addgroup -g 5010 opendkimSock && \
    addgroup opendkim opendkimSock

COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

HEALTHCHECK CMD ["sh", "-c", "pgrep opendkim >/dev/null && test -S /var/spool/postfix/opendkim/opendkim.sock"]

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["/entrypoint.sh"]